#index:
#    path: /
#    controller: App\Controller\DefaultController::index
security_registration:
  path:     /register
  defaults: { _controller: App\Controller\SecurityController::registration }

security_login:
  path:     /login
  defaults: { _controller: App\Controller\SecurityController::login }


security_logout:
  path:     /logout
  defaults: { _controller: App\Controller\SecurityController::logout }